apiVersion: v2
name: mealie
description: A Helm chart for deploying Mealie to a Kubernetes cluster.
type: application
version: 0.0.7
appVersion: "v1.0.0beta-5"

maintainers:
  - name: smarthall
    email: helm@danielhall.me
